### ISSUE TITLE
sort with limit applies limit first

### ISSUE THREAD

**Issue by keithnorm** [erikolson186/zangodb#9]
according to mongodb sort should be applied before limit, regardless of the chain order  https://docs.mongodb.com/manual/reference/method/db.collection.find/#combine-cursor-methods

what I'm seeing is the docs passed to the sort stage have already been limited (regardless of chain order), so the final result is wrong when limit < total docs count.

I just hit this and haven't dug in too much yet, but If you want I can investigate more and see if I can fix it.

**Comment by keithnorm** [comment]
I found what I think the problem is. This line https://github.com/erikolson186/zangodb/blob/master/src/create_next_fn.js#L164 pushes the sort stage to the end of the pipeline. I think it needs to prepend to the front of the pipeline instead.

**Comment by erikolson186** [comment]
Thank you for the pointing this out. Your suggested change to `unshift` works for when `limit` comes after `sort`. 

Though apparently when `limit` comes before `sort`, with either `unshift` or `push` for sort, the limit is applied before the sort.

**Comment by keithnorm** [comment]
It seems to me that `initPredAndSortSpec` enforces that `sort` and `filter` should be before any other stages in the pipeline. Is that really an invariant? If I'm reading your patch correctly if makes it so it will work as long as `sort`, `filter`, or `limit` come before any other stages, but will that always uphold too? I changed it like this:

```js
const initPredAndSortSpec = (config) => {
    const { pipeline } = config,
          preds = [],
          sort_specs = [];

    let toSplice = [];

    for (let [i, [fn, arg]] of pipeline.entries()) {
        if (fn === sort) { toSplice.push(i); sort_specs.push(arg); }
        else if (fn === filter) { toSplice.push(i); preds.push(arg); }
    }

    for (let idx of toSplice) {
      pipeline.splice(idx, 1);
    }

    config.pred = joinPredicates(preds);

    if (sort_specs.length) {
        config.sort_spec = sort_specs.reduce(merge, {});
    }
};
```

so it's ok for `filter` and `sort` to show up at any position in the pipeline. Though maybe that level of flexibility isn't necessary?

**Comment by erikolson186** [comment]
The `initPredAndSortSpec` operations are used as part of generating a query to possibly be used with an index.  The idea is that `filter` or `sort` could be referencing attributes that do not exist, or have been changed, due to operations such as `project`, `group`, and `unwind`. It seems that `limit` is fine, and possibly `skip`. It also seems that `project` should be fine in certain circumstances.

**Comment by erikolson186** [comment]
I just tested something with MongoDB. It turns out that with the aggregation pipeline `$limit` is evaluated before `$sort` when `$limit` comes before `$sort`.

These two examples do not yield the same results with MongoDB:

```javascript
// 1
foo.find().limit(3).sort({ x: 1 })

// 2
foo.aggregate([ { $limit: 3 }, { $sort: { x: 1 } }])
```
With ZangoDB, the operators of the aggregation pipeline are all available as methods of `Cursor`. This is different from MongoDB which has only `limit`, `skip`, and `sort`. 

The question for ZangoDB is whether or not to isolate the aggregation pipeline to only be used with the `aggregate` method, and have the available `Cursor` methods function more like MongoDB (such as ignoring limit and sort order in chained queries).

What is your take on this?

**Comment by keithnorm** [comment]
Yeah, interesting, I have two thoughts on that. One is I am writing an app where I rely on the results from a query on the client to be 100% identical to the same query run on the server, so that symmetry is very important.

But, in this case I don't feel like it's necessary to match mongo's behavior because ZangoDB's behavior feels more correct and more intuitive.

What do you think?

If you do choose to knowingly diverge from Mongo behavior, it might be nice to document the types of queries that may function differently on ZangoDB as compared to Mongo.

**Comment by erikolson186** [comment]
I agree with you. The goal is to have ZangoDB be compatible with MongoDB. However, in this case incompatibility seems like minor caveat for being more streamline.

The aggregation pipeline came to MongoDB quite late, making up for some significant shortcomings of the query language. It is possible that MongoDB would be more like ZangoDB if the pipeline was designed from the start.

I did some work developing an adapter system for ZangoDB. This way ZangoDB could be used with IndexedDB on the client and MongoDB on the server. Perhaps even a remote adapter too. Not sure if it would be worth completing though.
